### ISSUE TITLE
Intellectual property

### ISSUE THREAD

**Issue by ghost** [taniarascia/mvc#5]
Hi Tania!

Have you seen this https://github.com/pscully/simple-todo ?

I'm a bit confused by this situation. The code looks deceptively similar to yours, only the styles are different. I hope this is a misunderstanding because I can't see any credits there.

Have a good day!

**Comment by taniarascia** [comment]
It is my code, however this code is open source and freely available. Although I would like people to leave an attribution when they use it, there’s not much I can do if they decide not to.

**Comment by ghost** [comment]
Unfortunately. Thanks for the article and good luck!
